import pandas as pd

df = pd.read_csv('D:\ML\sample_data\california_housing_train.csv')
print(df.describe()) #to validate our assignment

'''
Housing Median Age
'''
hma = 'housing_median_age'
mean = df[hma].mean()
std_dev = df[hma].std()
mini = df[hma].min()
maxi = df[hma].max()
q1 = df[hma].quantile(.25)
q2 = df[hma].quantile(.5)
q3 = df[hma].quantile(.75)
empty = df[hma].isnull().sum(axis=0)

print("")
print('housing_median_age mean: ', mean)
print('housing_median_age standard deviation: ', std_dev)
print('housing_median_age min(value): ', mini)
print('housing_median_age max(value): ', maxi)
print('housing_median_age Q1: ', q1)
print('housing_median_age Q2: ', q2)
print('housing_median_age Q3: ', q3)
print('housing_median_age nilai kosong/nol: ', empty)

tr = 'total_rooms'
mean = df[tr].mean()
std_dev = df[tr].std()
mini = df[tr].min()
maxi = df[tr].max()
q1 = df[tr].quantile(.25)
q2 = df[tr].quantile(.5)
q3 = df[tr].quantile(.75)
empty = df[tr].isnull().sum(axis=0)

print("")
print('total_rooms mean: ', mean)
print('total_rooms standard deviation: ', std_dev)
print('total_rooms min(value): ', mini)
print('total_rooms max(value): ', maxi)
print('total_rooms Q1: ', q1)
print('total_rooms Q2: ', q2)
print('total_rooms Q3: ', q3)
print('total_rooms nilai kosong/nol: ', empty)

tb = 'total_bedrooms'
mean = df[tb].mean()
std_dev = df[tb].std()
mini = df[tb].min()
maxi = df[tb].max()
q1 = df[tb].quantile(.25)
q2 = df[tb].quantile(.5)
q3 = df[tb].quantile(.75)
empty = df[tb].isnull().sum(axis=0)

print("")
print('total_bedrooms mean: ', mean)
print('total_bedrooms standard deviation: ', std_dev)
print('total_bedrooms min(value): ', mini)
print('total_bedrooms max(value): ', maxi)
print('total_bedrooms Q1: ', q1)
print('total_bedrooms Q2: ', q2)
print('total_bedrooms Q3: ', q3)
print('total_bedrooms nilai kosong/nol: ', empty)

pop = 'population'
mean = df[pop].mean()
std_dev = df[pop].std()
mini = df[pop].min()
maxi = df[pop].max()
q1 = df[pop].quantile(.25)
q2 = df[pop].quantile(.5)
q3 = df[pop].quantile(.75)
empty = df[pop].isnull().sum(axis=0)

print("")
print('population mean: ', mean)
print('population standard deviation: ', std_dev)
print('population min(value): ', mini)
print('population max(value): ', maxi)
print('population Q1: ', q1)
print('population Q2: ', q2)
print('population Q3: ', q3)
print('population nilai kosong/nol: ', empty)

hh = 'households'
mean = df[hh].mean()
std_dev = df[hh].std()
mini = df[hh].min()
maxi = df[hh].max()
q1 = df[hh].quantile(.25)
q2 = df[hh].quantile(.5)
q3 = df[hh].quantile(.75)
empty = df[hh].isnull().sum(axis=0)

print("")
print('households mean: ', mean)
print('households standard deviation: ', std_dev)
print('households min(value): ', mini)
print('households max(value): ', maxi)
print('households Q1: ', q1)
print('households Q2: ', q2)
print('households Q3: ', q3)
print('households nilai kosong/nol: ', empty)

mi = 'median_income'
mean = df[mi].mean()
std_dev = df[mi].std()
mini = df[mi].min()
maxi = df[mi].max()
q1 = df[mi].quantile(.25)
q2 = df[mi].quantile(.5)
q3 = df[mi].quantile(.75)
empty = df[mi].isnull().sum(axis=0)

print("")
print('median_income mean: ', mean)
print('median_income standard deviation: ', std_dev)
print('median_income min(value): ', mini)
print('median_income max(value): ', maxi)
print('median_income Q1: ', q1)
print('median_income Q2: ', q2)
print('median_income Q3: ', q3)
print('median_income nilai kosong/nol: ', empty)

mhv = 'median_house_value'
mean = df[mhv].mean()
std_dev = df[mhv].std()
mini = df[mhv].min()
maxi = df[mhv].max()
q1 = df[mhv].quantile(.25)
q2 = df[mhv].quantile(.5)
q3 = df[mhv].quantile(.75)
empty = df[mhv].isnull().sum(axis=0)

print("")
print('median_house_value mean: ', mean)
print('median_house_value standard deviation: ', std_dev)
print('median_house_value min(value): ', mini)
print('median_house_value max(value): ', maxi)
print('median_house_value Q1: ', q1)
print('median_house_value Q2: ', q2)
print('median_house_value Q3: ', q3)
print('median_house_value nilai kosong/nol: ', empty)